FEATURE | use sql.Result as valid output parameter
jonbodner/proteus pull request #53
Opened 2021-01-10 20:19 UTC by kalexmills

This change enables the user to return an `sql.Result` in the first output parameter, provided they combine it with an Executor or ContextExecutor.

Tests included. I have not (yet) attempted to use it in my project.

2021-01-10 20:20 UTC, kalexmills commented
Closes #52

2021-01-10 21:03 UTC, kalexmills commented
FWIW this works for my use-case once I've integrated it.

2021-01-11 04:26 UTC, jonbodner commented
Do you have a GPG key to sign your commits? I was being picky, but if it's a problem, I can relax it.

2021-01-11 04:45 UTC, jonbodner requested changes
Thanks for this! Just a few small changes in two cases that weren't tested (only one return parameter and it's an error and a sql.Result, and the impossible one that I don't know how you'd test).

2021-01-11 04:45 UTC, jonbodner commented on runner.go
> +				return []reflect.Value{zeroInt64}
Need to handle returning either a zero value int64 or a zero value sql.Result, depending on sType.

2021-01-11 04:45 UTC, jonbodner commented on runner.go
> +		return []reflect.Value{zeroInt64, reflect.ValueOf(stackerr.New("should never get here"))}
need to handle sql.Result here too, even though it's an "impossible" case.

2021-01-12 04:32 UTC, jonbodner approved these changes
LGTM

2021-01-12 04:33 UTC, merged